### ISSUE TITLE
Package causes import issues due to lack of "assets"

### ISSUE THREAD

**Issue by SimonDarksideJ** [realitycollective/com.realitytoolkit.spatial-persistence.arfoundation#4]
Like other packages, the "~Assets" folder should contain default deployable content with the package, OR remove the installer scripts with no content.

Currently, this is causing an error because there is no content to install and makes Unity fall into a content load loop, constantly trying to install something that is not there.

**Comment by FejZa** [comment]
Was this resolved with the latest PR?

**Comment by SimonDarksideJ** [comment]
Sadly no @FejZa , Having actual profiles I believed would clear the import issue, however the issue remains with the following error reported in Unity on trying to import the assets with the Package Installer:

> DirectoryNotFoundException: Could not find a part of the path 'D:\00-Development\RCT\RCTTest-02\Library\PackageCache\com.realitytoolkit.spatialpersistence.arfoundation@49b6160e8f\Editor\SpatialPersistence_ARFoundationPathFinder.cs\Assets~'.
System.IO.Enumeration.FileSystemEnumerator1[TResult].CreateDirectoryHandle (System.String path, System.Boolean ignoreNotFound) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
System.IO.Enumeration.FileSystemEnumerator1[TResult]..ctor (System.String directory, System.IO.EnumerationOptions options) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
System.IO.Enumeration.FileSystemEnumerable1+DelegateEnumerator[TResult]..ctor (System.IO.Enumeration.FileSystemEnumerable1[TResult] enumerable) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
System.IO.Enumeration.FileSystemEnumerable1[TResult]..ctor (System.String directory, System.IO.Enumeration.FileSystemEnumerable1+FindTransform[TResult] transform, System.IO.EnumerationOptions options) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles (System.String directory, System.String expression, System.IO.EnumerationOptions options) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
System.IO.Directory.InternalEnumeratePaths (System.String path, System.String searchPattern, System.IO.SearchTarget searchTarget, System.IO.EnumerationOptions options) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
System.IO.Directory.GetFiles (System.String path, System.String searchPattern, System.IO.EnumerationOptions enumerationOptions) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
System.IO.Directory.GetFiles (System.String path, System.String searchPattern, System.IO.SearchOption searchOption) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
RealityCollective.Editor.Utilities.UnityFileHelper.GetAllFilesAtPath (System.String assetsRootPath) (at ./Library/PackageCache/com.realitycollective.utilities@1.0.5-pre.3/Editor/Utilities/UnityFileHelper.cs:66)
RealityCollective.ServiceFramework.Editor.Packages.AssetsInstaller.TryInstallAssets (System.Collections.Generic.Dictionary`2[TKey,TValue] installationPaths, System.Boolean regenerateGuids, System.Boolean skipDialog, System.Boolean onlyUnityAssets) (at ./Library/PackageCache/com.realitycollective.service-framework@1.0.3-pre.6/Editor/Packages/AssetsInstaller.cs:116)
RealityCollective.ServiceFramework.Editor.Packages.AssetsInstaller.TryInstallAssets (System.String sourcePath, System.String destinationPath, System.Boolean regenerateGuids, System.Boolean skipDialog, System.Boolean onlyUnityAssets) (at ./Library/PackageCache/com.realitycollective.service-framework@1.0.3-pre.6/Editor/Packages/AssetsInstaller.cs:51)
RealityToolkit.SpatialPersistence.ARFoundation.Editor.SpatialPersistence_ARFoundationPackageInstaller.CheckPackage () (at
./Library/PackageCache/com.realitytoolkit.spatialpersistence.arfoundation@49b6160e8f/Editor/SpatialPersistence_ARFoundationPackageInstaller.cs:43)
UnityEditor.EditorApplication.Internal_CallDelayFunctions () (at <9920ff0c944845d7b9f9a61ef1478edc>:0)

 Can you help?
